version: '3'
services:
  app:
    container_name: ollama-web-ui
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - OLLAMA_API_BASE_URL=${MY_API}
    ports:
      - "5173:8080"
